export const namesData = [
  // ── HEROES OF FAITH ──
  {
    name: "ABRAHAM",
    pronunciation: "AY-bruh-ham",
    meaning: "Father of Many Nations",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "Abraham left everything he knew — his home, his country, his people — simply because God asked him to. He trusted God so completely that when God promised him more descendants than stars in the sky, Abraham believed it even though he was nearly 100 years old. His faith was so extraordinary that he is called the father of all who believe.",
    verse: "By faith Abraham obeyed when he was called to go out to a place that he was to receive as an inheritance. And he went out, not knowing where he was going.",
    verseRef: "Hebrews 11:8",
  },
  {
    name: "MOSES",
    pronunciation: "MOH-zez",
    meaning: "Drawn Out of the Water",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "Moses was rescued from a river as a baby, raised in a palace, and then chosen by God to rescue an entire nation from slavery. He parted the Red Sea, received the Ten Commandments on a mountaintop, and led over a million people through the wilderness for forty years. When he spoke, even Pharaoh — the most powerful man on earth — eventually listened.",
    verse: "By faith Moses left Egypt, not being afraid of the anger of the king, for he endured as seeing him who is invisible.",
    verseRef: "Hebrews 11:27",
  },
  {
    name: "DAVID",
    pronunciation: "DAY-vid",
    meaning: "Beloved",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "David was just a shepherd boy when he walked onto a battlefield and killed a giant named Goliath with a single stone from a slingshot. He went on to become Israel's greatest king, a brilliant poet who wrote the Psalms, and a man God called 'a man after my own heart.' His story proves that God chooses people the world overlooks.",
    verse: "The Lord does not look at the things people look at. People look at the outward appearance, but the Lord looks at the heart.",
    verseRef: "1 Samuel 16:7",
  },
  {
    name: "NOAH",
    pronunciation: "NOH-uh",
    meaning: "Rest, Comfort",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "Noah built a massive boat in the middle of dry land while everyone around him laughed. It had never rained before, but God had told him a flood was coming. Noah trusted God and kept building. When the rains finally came, the ark he built saved his family and every species of animal — and after the flood, God placed a rainbow in the sky as His promise to never flood the earth again.",
    verse: "Noah did everything just as God commanded him.",
    verseRef: "Genesis 6:22",
  },
  {
    name: "ELIJAH",
    pronunciation: "ee-LY-juh",
    meaning: "My God is Yahweh",
    testament: "OT",
    gender: "male",
    pack: "prophets",
    story: "Elijah was one of the most powerful prophets in the Bible. When the evil King Ahab turned Israel away from God, Elijah boldly stood alone against 450 false prophets — and called down fire from heaven to prove that the God of Israel was real. He was so faithful that God took him to heaven in a chariot of fire without him ever dying.",
    verse: "The fire of the Lord fell and burned up the sacrifice, the wood, the stones and the soil, and also licked up the water in the trench.",
    verseRef: "1 Kings 18:38",
  },
  {
    name: "JOSHUA",
    pronunciation: "JOSH-yoo-uh",
    meaning: "God is Salvation",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "Joshua took over where Moses left off and led the Israelites into the Promised Land. His most famous moment came at the city of Jericho — instead of using weapons, God told him to march his army around the city walls for seven days and blow trumpets. When they did, the walls fell down flat. Joshua proved that obedience is always the right strategy.",
    verse: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.",
    verseRef: "Joshua 1:9",
  },
  {
    name: "SAMUEL",
    pronunciation: "SAM-yoo-el",
    meaning: "God Has Heard",
    testament: "OT",
    gender: "male",
    pack: "prophets",
    story: "Samuel heard God's voice for the first time as a young boy sleeping in the temple. He thought someone was calling his name but it was God Himself. Samuel grew up to become one of Israel's greatest prophets and judges — the man who anointed both Saul and David as kings of Israel. He showed that God speaks to people of any age.",
    verse: "Speak, Lord, for your servant is listening.",
    verseRef: "1 Samuel 3:9",
  },
  {
    name: "DANIEL",
    pronunciation: "DAN-yel",
    meaning: "God is My Judge",
    testament: "OT",
    gender: "male",
    pack: "prophets",
    story: "Daniel was thrown into a den of hungry lions because he refused to stop praying to God. He prayed three times a day no matter what, even when the king made it illegal. When morning came and the king ran to the lion's den calling out Daniel's name, Daniel answered from inside — completely unharmed. The lions hadn't touched him. God had shut their mouths.",
    verse: "My God sent his angel, and he shut the mouths of the lions. They have not hurt me, because I was found innocent in his sight.",
    verseRef: "Daniel 6:22",
  },
  {
    name: "JOSEPH",
    pronunciation: "JOH-zef",
    meaning: "He Will Add",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "Joseph's brothers were so jealous of him that they sold him into slavery. He was falsely accused of a crime and thrown in prison. But everywhere Joseph went, God was with him and gave him favor. He went from prison to becoming the second most powerful man in Egypt — and ended up saving the very brothers who betrayed him, saying 'You meant evil against me, but God meant it for good.'",
    verse: "You intended to harm me, but God intended it for good to accomplish what is now being done, the saving of many lives.",
    verseRef: "Genesis 50:20",
  },
  {
    name: "GIDEON",
    pronunciation: "GID-ee-un",
    meaning: "Mighty Warrior",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "When God called Gideon a 'mighty warrior,' Gideon was hiding in a winepress threshing wheat so the enemy wouldn't find him. He was the least in his family and the weakest in his tribe. But God whittled his army down from 32,000 soldiers to just 300 men — then gave them a miraculous victory over an army of 135,000. God specializes in using the unlikely.",
    verse: "The Lord is with you, mighty warrior.",
    verseRef: "Judges 6:12",
  },
  // ── WOMEN OF THE BIBLE ──
  {
    name: "RUTH",
    pronunciation: "ROOTH",
    meaning: "Companion, Friend",
    testament: "OT",
    gender: "female",
    pack: "women",
    story: "Ruth was not even an Israelite, but she became one of the most celebrated women in all of Scripture. When her husband died, she refused to abandon her mother-in-law Naomi, saying 'Where you go I will go, and where you stay I will stay.' Her extraordinary loyalty led her to a new life in Israel — and she became the great-grandmother of King David and an ancestor of Jesus Himself.",
    verse: "Where you go I will go, and where you stay I will stay. Your people will be my people and your God my God.",
    verseRef: "Ruth 1:16",
  },
  {
    name: "ESTHER",
    pronunciation: "ES-ter",
    meaning: "Star",
    testament: "OT",
    gender: "female",
    pack: "women",
    story: "Esther was an orphan who became a queen — and then risked her life to save her entire people. When a powerful official named Haman plotted to destroy all the Jews in the Persian empire, Esther went before the king uninvited (which could mean death) to beg for their lives. Her courage saved a nation, and her story reminds us that perhaps you were born for such a time as this.",
    verse: "Who knows whether you have not come to the kingdom for such a time as this?",
    verseRef: "Esther 4:14",
  },
  {
    name: "DEBORAH",
    pronunciation: "DEB-oh-ruh",
    meaning: "Bee",
    testament: "OT",
    gender: "female",
    pack: "women",
    story: "Deborah was a prophet, a judge, and a military commander — all at once — at a time when women rarely held any public role. She would sit under a palm tree and people would come from all over Israel to have her settle their disputes. When it was time for battle, she rode into war alongside her general and led Israel to a stunning victory. She was one of the most powerful leaders in Israel's entire history.",
    verse: "Villagers in Israel would not fight; they held back until I, Deborah, arose, until I arose, a mother in Israel.",
    verseRef: "Judges 5:7",
  },
  {
    name: "MARY",
    pronunciation: "MAIR-ee",
    meaning: "Beloved, Bitter Sea",
    testament: "NT",
    gender: "female",
    pack: "women",
    story: "Mary was a young teenager living a quiet life when an angel appeared and told her she would carry the Son of God. She had no idea what that would mean — the midnight flight to Egypt, raising a child who performed miracles, and standing at a cross watching her son die. Through all of it, her first answer to God was simply 'Let it be to me according to your word.' She is the most mentioned woman in all of Scripture.",
    verse: "I am the Lord's servant. May it be to me as you have said.",
    verseRef: "Luke 1:38",
  },
  {
    name: "HANNAH",
    pronunciation: "HAN-uh",
    meaning: "Grace, Favor",
    testament: "OT",
    gender: "female",
    pack: "women",
    story: "Hannah wept so hard in prayer at the temple that the priest thought she was drunk. She desperately wanted a child but had been unable to conceive for years. She poured her heart out to God and made a promise: if He gave her a son, she would give the child back to serve God. God heard her prayer, gave her Samuel, and she kept her promise. Her prayer of praise became one of the most beautiful poems in the Bible.",
    verse: "My heart rejoices in the Lord; in the Lord my horn is lifted high.",
    verseRef: "1 Samuel 2:1",
  },
  {
    name: "SARAH",
    pronunciation: "SAIR-uh",
    meaning: "Princess, Noblewoman",
    testament: "OT",
    gender: "female",
    pack: "women",
    story: "Sarah laughed when she overheard the angels tell her husband Abraham that she would have a baby — she was 90 years old. But God kept His promise, and she gave birth to Isaac, whose name means 'laughter.' Sarah's laugh of disbelief became a laugh of joy. Her story is a reminder that nothing is impossible for God, even when the whole idea seems laughable.",
    verse: "Is anything too hard for the Lord? I will return to you at the appointed time next year, and Sarah will have a son.",
    verseRef: "Genesis 18:14",
  },
  {
    name: "MIRIAM",
    pronunciation: "MEER-ee-um",
    meaning: "Beloved, Wished-for Child",
    testament: "OT",
    gender: "female",
    pack: "women",
    story: "Miriam was Moses' older sister, and she watched over his basket in the river as a little girl, making sure he was safe. Years later, after the Israelites crossed the Red Sea and the Egyptian army was destroyed, Miriam led the entire nation in a victory song — dancing and playing tambourine while all the women followed her. She was one of the three leaders God appointed to guide Israel out of Egypt.",
    verse: "Sing to the Lord, for he is highly exalted. Both horse and driver he has hurled into the sea.",
    verseRef: "Exodus 15:21",
  },
  {
    name: "LYDIA",
    pronunciation: "LID-ee-uh",
    meaning: "From Lydia",
    testament: "NT",
    gender: "female",
    pack: "women",
    story: "Lydia was a successful businesswoman who sold purple cloth — a luxury item in the ancient world. When Paul and his companions arrived in Philippi, they found Lydia gathered with other women in prayer by a river. She listened to Paul preach, and the Bible says 'the Lord opened her heart.' She was the first person in Europe to become a Christian, and she immediately opened her home to Paul's entire missionary team.",
    verse: "The Lord opened her heart to respond to Paul's message.",
    verseRef: "Acts 16:14",
  },
  // ── KINGS & RULERS ──
  {
    name: "SOLOMON",
    pronunciation: "SOL-uh-mun",
    meaning: "Peace",
    testament: "OT",
    gender: "male",
    pack: "kings",
    story: "When God offered Solomon anything he wanted, the young king didn't ask for wealth, power, or long life — he asked for wisdom. God was so pleased that He gave Solomon wisdom greater than any person who had ever lived, and then gave him wealth and honor on top of it. Solomon built the magnificent Temple in Jerusalem and wrote thousands of proverbs, many of which are still read every day.",
    verse: "Give your servant a discerning heart to govern your people and to distinguish between right and wrong.",
    verseRef: "1 Kings 3:9",
  },
  {
    name: "HEZEKIAH",
    pronunciation: "hez-uh-KY-uh",
    meaning: "God is My Strength",
    testament: "OT",
    gender: "male",
    pack: "kings",
    story: "When the massive Assyrian army surrounded Jerusalem and the situation looked completely hopeless, King Hezekiah spread the enemy's threatening letter out before God in the Temple and prayed. That night, the angel of the Lord struck down 185,000 Assyrian soldiers — and Jerusalem was saved without a single battle. Hezekiah also prayed when doctors said he was dying, and God added 15 years to his life.",
    verse: "Lord, the God of Israel, enthroned between the cherubim, you alone are God over all the kingdoms of the earth.",
    verseRef: "2 Kings 19:15",
  },
  {
    name: "JOSIAH",
    pronunciation: "joh-ZY-uh",
    meaning: "God Supports and Heals",
    testament: "OT",
    gender: "male",
    pack: "kings",
    story: "Josiah became king of Judah when he was just eight years old. By the time he was a teenager, he had already begun tearing down the pagan altars his evil grandfather had built. When workers found a long-lost copy of God's law during Temple renovations, Josiah read it and wept — then launched the most sweeping religious reform in Israel's history. He was described as a king who turned to God 'with all his heart and soul and strength.'",
    verse: "Neither before nor after Josiah was there a king like him who turned to the Lord as he did — with all his heart and with all his soul and with all his strength.",
    verseRef: "2 Kings 23:25",
  },
  {
    name: "JEHOSHAPHAT",
    pronunciation: "jeh-HOSH-uh-fat",
    meaning: "God Has Judged",
    testament: "OT",
    gender: "male",
    pack: "kings",
    story: "When three armies came against King Jehoshaphat at once, he did something unusual — he sent the worship choir out in front of the army to sing praise to God. As they sang, God set ambushes among the enemy armies and they destroyed each other. By the time Jehoshaphat's army arrived, there was nothing left to do but collect the plunder. It took three days to haul it all away.",
    verse: "Do not be afraid or discouraged because of this vast army. For the battle is not yours, but God's.",
    verseRef: "2 Chronicles 20:15",
  },
  // ── PROPHETS ──
  {
    name: "ISAIAH",
    pronunciation: "eye-ZAY-uh",
    meaning: "God is Salvation",
    testament: "OT",
    gender: "male",
    pack: "prophets",
    story: "Isaiah had a vision of God sitting on a throne so magnificent that the train of His robe filled the entire temple, and angels surrounded Him crying 'Holy, holy, holy!' Isaiah was so overwhelmed by God's holiness that he cried out that he was undone. But God touched his lips with a burning coal and sent him as a prophet. Isaiah then wrote some of the most breathtaking prophecies about Jesus — written 700 years before Jesus was born.",
    verse: "He was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds we are healed.",
    verseRef: "Isaiah 53:5",
  },
  {
    name: "JEREMIAH",
    pronunciation: "jair-uh-MY-uh",
    meaning: "God Will Exalt",
    testament: "OT",
    gender: "male",
    pack: "prophets",
    story: "Jeremiah is sometimes called the 'weeping prophet' because he had one of the hardest jobs in the Bible — telling people they needed to repent when they didn't want to hear it. He was thrown into a muddy cistern, put in stocks, and rejected by nearly everyone. But he kept speaking God's word for over 40 years. He also wrote that God says 'I know the plans I have for you — plans to prosper you and not to harm you, plans to give you hope and a future.'",
    verse: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.",
    verseRef: "Jeremiah 29:11",
  },
  {
    name: "EZEKIEL",
    pronunciation: "ee-ZEE-kee-el",
    meaning: "God Strengthens",
    testament: "OT",
    gender: "male",
    pack: "prophets",
    story: "Ezekiel had some of the most dramatic visions in all of the Bible — including a valley full of dry, dead bones that God told him to speak to. As Ezekiel preached, the bones rattled together, grew muscles and skin, and came back to life as a great army. The vision was a picture of how God can breathe new life into people and nations that seem completely dead. Ezekiel showed that no situation is too far gone for God.",
    verse: "I will put my Spirit in you and you will live.",
    verseRef: "Ezekiel 37:14",
  },
  {
    name: "JONAH",
    pronunciation: "JOH-nuh",
    meaning: "Dove",
    testament: "OT",
    gender: "male",
    pack: "prophets",
    story: "Jonah ran in the opposite direction when God told him to preach to the wicked city of Nineveh. He boarded a ship heading the other way — and ended up in the belly of a giant fish for three days. When the fish spit him out on dry land, Jonah finally went to Nineveh. He preached, the entire city repented, and God spared them. Jonah's story shows that you can't outrun God's call — and that His mercy reaches even the people we think don't deserve it.",
    verse: "From inside the fish Jonah prayed to the Lord his God.",
    verseRef: "Jonah 2:1",
  },
  // ── NEW TESTAMENT ──
  {
    name: "PETER",
    pronunciation: "PEE-ter",
    meaning: "Rock",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Peter was a rough, impulsive fisherman who became one of Jesus' closest friends. He was the one who stepped out of a boat and walked on water — until he looked at the waves and started to sink. He also denied knowing Jesus three times on the night Jesus was arrested, and wept bitterly over it. But Jesus personally restored him and said 'Feed my sheep.' Peter went on to preach the first Christian sermon, saw 3,000 people saved, and ultimately gave his life for his faith.",
    verse: "And I tell you that you are Peter, and on this rock I will build my church, and the gates of Hades will not overcome it.",
    verseRef: "Matthew 16:18",
  },
  {
    name: "PAUL",
    pronunciation: "PAWL",
    meaning: "Humble, Small",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Paul started out as the church's most dangerous enemy — traveling from city to city arresting and executing Christians. Then one day a blinding light knocked him off his horse and the voice of Jesus spoke to him. Paul's life flipped completely. He became the greatest missionary in history, planted churches across three continents, wrote 13 books of the New Testament, survived shipwrecks and beatings, and changed the world forever.",
    verse: "I can do all this through him who gives me strength.",
    verseRef: "Philippians 4:13",
  },
  {
    name: "JOHN",
    pronunciation: "JON",
    meaning: "God is Gracious",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "John called himself 'the disciple Jesus loved' — not out of arrogance, but because he was so overwhelmed by God's love for him. He was one of the three disciples closest to Jesus, present at the Transfiguration, the Garden of Gethsemane, and the empty tomb. He wrote five books of the New Testament, including the Gospel of John, three letters, and the book of Revelation. He lived to an old age and kept one simple message: love one another.",
    verse: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.",
    verseRef: "John 3:16",
  },
  {
    name: "STEPHEN",
    pronunciation: "STEE-ven",
    meaning: "Crown, Wreath",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Stephen was the first Christian martyr — the first person to die for his faith in Jesus. He was a deacon in the early church known for being full of faith and the Holy Spirit. When he stood before the religious council and boldly proclaimed the truth, they dragged him outside and stoned him to death. As they threw stones, Stephen looked up and saw heaven opened and Jesus standing at the right hand of God. His last words were a prayer forgiving the people killing him.",
    verse: "Look, I see heaven open and the Son of Man standing at the right hand of God.",
    verseRef: "Acts 7:56",
  },
  {
    name: "TIMOTHY",
    pronunciation: "TIM-oh-thee",
    meaning: "Honoring God",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Timothy was a young man who became one of Paul's most trusted partners in ministry. Paul called him 'my true son in the faith.' Timothy was shy and reportedly somewhat timid, and Paul had to encourage him to not let anyone look down on him because of his youth. Two of Paul's letters in the Bible are written directly to Timothy, packed with advice about leading the church, staying faithful, and fighting the good fight of faith.",
    verse: "Don't let anyone look down on you because you are young, but set an example for the believers in speech, in conduct, in love, in faith and in purity.",
    verseRef: "1 Timothy 4:12",
  },
  {
    name: "BARNABAS",
    pronunciation: "BAR-nuh-bus",
    meaning: "Son of Encouragement",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "When Paul first came to Jerusalem after his dramatic conversion, everyone was terrified of him — they thought it was a trick. Barnabas was the one person who stepped forward, vouched for Paul, and brought him into the fellowship. His name literally means 'Son of Encouragement,' and he lived up to it. He was always the first to see potential in people others had given up on. Without Barnabas, Paul's ministry might never have started.",
    verse: "He was a good man, full of the Holy Spirit and faith, and a great number of people were brought to the Lord.",
    verseRef: "Acts 11:24",
  },
  {
    name: "ANDREW",
    pronunciation: "AN-droo",
    meaning: "Strong, Manly",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Andrew was the first disciple Jesus called, and the very first thing he did after meeting Jesus was run to find his brother Simon Peter and bring him too. Andrew was always the one bringing people to Jesus — he brought the boy with five loaves and two fish to Jesus at the feeding of the 5,000. He wasn't always in the spotlight, but he was always connecting people to the One who matters most.",
    verse: "The first thing Andrew did was to find his brother Simon and tell him, 'We have found the Messiah.'",
    verseRef: "John 1:41",
  },
  {
    name: "LAZARUS",
    pronunciation: "LAZ-uh-rus",
    meaning: "God is My Help",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Lazarus was one of Jesus' closest friends — and he died. By the time Jesus arrived, Lazarus had been in the tomb for four days. His sisters Mary and Martha were heartbroken. Jesus wept alongside them, then walked to the tomb and called out 'Lazarus, come out!' — and a dead man walked out still wrapped in burial cloths. It was the greatest miracle Jesus performed before His own resurrection, a preview of the power over death He holds.",
    verse: "Jesus said to her, 'I am the resurrection and the life. The one who believes in me will live, even though they die.'",
    verseRef: "John 11:25",
  },
  // ── MORE HEROES / MIXED ──
  {
    name: "CALEB",
    pronunciation: "KAY-leb",
    meaning: "Faithful, Wholehearted",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "When twelve spies scouted the Promised Land, ten came back terrified by the giants they saw. Caleb and Joshua were the only two who said 'We can do it — with God on our side!' Because of his wholehearted faith, Caleb was the only man of his generation allowed to enter the Promised Land. At 85 years old, he was still strong and bold, asking Joshua to give him the territory with the biggest giants so he could drive them out.",
    verse: "Because my servant Caleb has a different spirit and follows me wholeheartedly, I will bring him into the land he went to.",
    verseRef: "Numbers 14:24",
  },
  {
    name: "NATHANIEL",
    pronunciation: "nuh-THAN-ee-el",
    meaning: "Gift of God",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "When Philip told Nathaniel about Jesus of Nazareth, Nathaniel scoffed — 'Can anything good come from Nazareth?' But when Jesus saw Nathaniel approaching, He said 'Here truly is an Israelite in whom there is no deceit.' Nathaniel was stunned that Jesus already knew him. Jesus said He had seen Nathaniel sitting under a fig tree before they ever met. Nathaniel immediately declared 'You are the Son of God — you are the King of Israel!'",
    verse: "Here truly is an Israelite in whom there is no deceit.",
    verseRef: "John 1:47",
  },
  {
    name: "SILAS",
    pronunciation: "SY-lus",
    meaning: "Forest, Woods",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Silas was thrown into a Philippian prison with Paul after they cast a spirit out of a fortune-telling slave girl. With their feet in stocks and their backs bleeding from a severe beating, Paul and Silas did the remarkable — they sang hymns of praise to God at midnight. Suddenly an earthquake shook the prison, every door flew open, and everyone's chains fell off. The terrified jailer fell before them asking 'What must I do to be saved?'",
    verse: "About midnight Paul and Silas were praying and singing hymns to God, and the other prisoners were listening to them.",
    verseRef: "Acts 16:25",
  },
  {
    name: "PHILEMON",
    pronunciation: "fih-LEE-mun",
    meaning: "Affectionate, Friendly",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Philemon was a wealthy Christian man who had a runaway slave named Onesimus — who later became a Christian through Paul's ministry. Paul wrote one of the most personal letters in the entire Bible to Philemon, asking him to receive Onesimus back not as a slave but as a brother. The entire book of Philemon is a masterclass in grace, forgiveness, and how the Gospel transforms every relationship it touches.",
    verse: "Perhaps the reason he was separated from you for a little while was that you might have him back forever — no longer as a slave, but better than a slave, as a dear brother.",
    verseRef: "Philemon 1:15-16",
  },
  {
    name: "ENOCH",
    pronunciation: "EE-nuk",
    meaning: "Dedicated, Trained",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "Enoch holds one of the most mysterious distinctions in all of Scripture — he never died. The Bible simply says 'Enoch walked faithfully with God; then he was no more, because God took him away.' While everyone else in the genealogy has a death recorded, Enoch's line just ends with God taking him. He walked so closely with God that one day God simply kept him. His life raises a beautiful question: what does it look like to walk with God every single day?",
    verse: "Enoch walked faithfully with God; then he was no more, because God took him away.",
    verseRef: "Genesis 5:24",
  },
  {
    name: "BOAZ",
    pronunciation: "BOH-az",
    meaning: "Strength, Swiftness",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "Boaz was a wealthy landowner who noticed a foreign widow named Ruth working in his fields. He gave her extra grain, told his workers to leave grain behind on purpose for her, and made sure no one bothered her. He eventually married Ruth and became the 'kinsman-redeemer' who rescued her family from poverty. His character — generous, protective, honorable — made him a beautiful picture of what it means to love your neighbor. He became the great-grandfather of King David.",
    verse: "The Lord repay you for what you have done, and a full reward be given you by the Lord, the God of Israel, under whose wings you have come to take refuge.",
    verseRef: "Ruth 2:12",
  },
  {
    name: "MICAH",
    pronunciation: "MY-kuh",
    meaning: "Who is Like God?",
    testament: "OT",
    gender: "male",
    pack: "prophets",
    story: "Micah was a prophet from a small country village who had the courage to preach to the powerful — kings, priests, and false prophets who told people only what they wanted to hear. He also wrote one of the most quoted lines in all of Scripture, summing up what God actually wants from human beings in just a few words. He even predicted that the Messiah would be born in Bethlehem — 700 years before it happened.",
    verse: "He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God.",
    verseRef: "Micah 6:8",
  },
  {
    name: "AMOS",
    pronunciation: "AY-mus",
    meaning: "Borne by God",
    testament: "OT",
    gender: "male",
    pack: "prophets",
    story: "Amos was not a professional prophet — he was a shepherd and a fig farmer. He had no formal training or religious title. But God called him to leave his flock and go speak truth to the powerful leaders of Israel who were living in luxury while the poor starved. Amos's voice roared like a lion against injustice, reminding everyone that God cares deeply about how the vulnerable are treated.",
    verse: "But let justice roll on like a river, righteousness like a never-failing stream!",
    verseRef: "Amos 5:24",
  },
  {
    name: "HOSEA",
    pronunciation: "hoh-ZAY-uh",
    meaning: "Salvation",
    testament: "OT",
    gender: "male",
    pack: "prophets",
    story: "God asked Hosea to do something heartbreaking — marry a woman who would be unfaithful to him — so that Hosea would understand exactly how God felt about Israel's unfaithfulness. When his wife Gomer left and fell into slavery, God told Hosea to buy her back and love her again. Hosea did it. The whole story is a living portrait of God's relentless, pursuing love for people who keep turning away.",
    verse: "I will heal their waywardness and love them freely, for my anger has turned away from them.",
    verseRef: "Hosea 14:4",
  },
  {
    name: "MALACHI",
    pronunciation: "MAL-uh-ky",
    meaning: "My Messenger",
    testament: "OT",
    gender: "male",
    pack: "prophets",
    story: "Malachi was the last prophet of the Old Testament — the final voice before 400 years of silence before John the Baptist and Jesus arrived. He delivered a message of both warning and hope to a people who had grown cold in their faith. His book ends with a stunning promise that God would send a messenger to prepare the way, and that the sun of righteousness would rise with healing in its wings. The Old Testament closes on this note of anticipation.",
    verse: "But for you who revere my name, the sun of righteousness will rise with healing in its rays.",
    verseRef: "Malachi 4:2",
  },
  {
    name: "NEHEMIAH",
    pronunciation: "nee-huh-MY-uh",
    meaning: "God Comforts",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "Nehemiah was a cupbearer to the Persian king — basically a royal butler. When he heard that the walls of Jerusalem lay in ruins, he sat down and wept, fasted, and prayed for days. Then he asked the king for permission to go rebuild — and the king said yes. Nehemiah organized the entire city, armed workers with tools in one hand and swords in the other, and rebuilt Jerusalem's walls in just 52 days while enemies mocked and threatened him constantly.",
    verse: "The God of heaven will give us success. We his servants will start rebuilding.",
    verseRef: "Nehemiah 2:20",
  },
  {
    name: "EZRA",
    pronunciation: "EZ-ruh",
    meaning: "Help",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "Ezra was a scholar and scribe who devoted his entire life to studying, obeying, and teaching God's Word. When the Jewish people returned from exile in Babylon, Ezra led a group back to Jerusalem on a dangerous journey with no military escort — trusting God's protection the whole way. When he read the law aloud to the returned exiles, people wept with joy. Ezra rebuilt not just walls but hearts.",
    verse: "Ezra had devoted himself to the study and observance of the Law of the Lord, and to teaching its decrees and laws in Israel.",
    verseRef: "Ezra 7:10",
  },
  {
    name: "ZACCHAEUS",
    pronunciation: "zak-EE-us",
    meaning: "Pure, Innocent",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Zacchaeus was a wealthy tax collector — hated by everyone because he worked for the Roman occupiers and cheated people. He was also very short. When Jesus came through Jericho, Zacchaeus climbed a sycamore tree just to see Him over the crowd. Jesus looked up, called him by name, and invited Himself to dinner. That one encounter transformed Zacchaeus completely — he gave half his wealth to the poor and repaid everyone he had cheated four times over.",
    verse: "For the Son of Man came to seek and to save the lost.",
    verseRef: "Luke 19:10",
  },
  {
    name: "MATTHIAS",
    pronunciation: "muh-THY-us",
    meaning: "Gift of God",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Matthias had been a follower of Jesus from the very beginning — present at the baptism of John all the way through the resurrection — but was never in the famous circle of twelve. After Judas betrayed Jesus and was gone, the disciples gathered and chose Matthias by casting lots to fill the empty spot among the twelve apostles. He reminds us that faithful, quiet disciples matter deeply even when they are not in the spotlight.",
    verse: "So they nominated two men... Then they cast lots, and the lot fell to Matthias; so he was added to the eleven apostles.",
    verseRef: "Acts 1:23-26",
  },
  {
    name: "NICODEMUS",
    pronunciation: "nik-oh-DEE-mus",
    meaning: "Victory of the People",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Nicodemus was a powerful religious leader who came to visit Jesus secretly at night — he was curious but afraid of what people would think. Jesus told him 'You must be born again,' and gave him what became the most quoted verse in the Bible. Nicodemus went away confused, but something changed in him. Later he defended Jesus publicly in the temple courts, and after the crucifixion, he and Joseph of Arimathea were the ones who lovingly prepared Jesus' body for burial.",
    verse: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.",
    verseRef: "John 3:16",
  },
  // ── MORE WOMEN ──
  {
    name: "ABIGAIL",
    pronunciation: "AB-ih-gayl",
    meaning: "Father's Joy",
    testament: "OT",
    gender: "female",
    pack: "women",
    story: "Abigail was married to a foolish, mean man named Nabal. When David's men came to Nabal for food and hospitality after protecting his livestock, Nabal rudely refused them. David was furious and headed to take revenge. Abigail quickly loaded up donkeys with food and rode out to intercept David, bowing humbly and begging him not to shed innocent blood. Her wisdom and courage stopped a massacre. David was so impressed he later married her after Nabal died.",
    verse: "When Abigail saw David, she quickly got off her donkey and bowed down before David with her face to the ground.",
    verseRef: "1 Samuel 25:23",
  },
  {
    name: "RACHEL",
    pronunciation: "RAY-chel",
    meaning: "Ewe, Little Lamb",
    testament: "OT",
    gender: "female",
    pack: "women",
    story: "Jacob loved Rachel so much that he worked seven years to marry her — and the Bible says the years 'seemed like only a few days to him because of his love for her.' Then her father tricked him and gave him the wrong daughter, and Jacob had to work another seven years. Rachel eventually became the mother of Joseph (of the many-colored coat) and Benjamin, and her lineage became one of the great tribes of Israel.",
    verse: "So Jacob served seven years to get Rachel, but they seemed like only a few days to him because of his love for her.",
    verseRef: "Genesis 29:20",
  },
  {
    name: "PRISCILLA",
    pronunciation: "prih-SIL-uh",
    meaning: "Ancient, Venerable",
    testament: "NT",
    gender: "female",
    pack: "women",
    story: "Priscilla and her husband Aquila were tentmakers, just like Paul, and they became two of his most important coworkers in ministry. When they heard a brilliant preacher named Apollos teaching about Jesus but with incomplete understanding, Priscilla and Aquila didn't criticize him publicly — they took him aside privately and explained the way of God more accurately. Apollos went on to become a powerful preacher. Priscilla shows that discipleship often happens in private conversations.",
    verse: "He began to speak boldly in the synagogue. When Priscilla and Aquila heard him, they invited him to their home and explained to him the way of God more adequately.",
    verseRef: "Acts 18:26",
  },
  {
    name: "NAOMI",
    pronunciation: "nay-OH-mee",
    meaning: "Pleasant, Sweet",
    testament: "OT",
    gender: "female",
    pack: "women",
    story: "Naomi lost her husband and both her sons in a foreign land, leaving her completely alone with two daughters-in-law. She told them to go back to their families and find new husbands — she had nothing left to offer. One daughter left, but Ruth refused to go. Naomi returned to Israel bitter and broken, telling people to call her 'Mara' which means bitter. But through Ruth's faithfulness and Boaz's love, God restored everything Naomi had lost.",
    verse: "Return home, my daughters. Why would you come with me? Am I going to have any more sons, who could become your husbands?",
    verseRef: "Ruth 1:11",
  },
  // ── MORE OT HEROES ──
  {
    name: "AARON",
    pronunciation: "AIR-un",
    meaning: "Exalted, Strong",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "Aaron was Moses' older brother and his right-hand man through the entire Exodus. When Moses felt too tongue-tied to speak to Pharaoh, God appointed Aaron to be his spokesman. Aaron held up Moses' arms during the battle against the Amalekites — and as long as Moses' arms were raised, Israel was winning. Aaron became Israel's first High Priest, representing the people before God at the altar, a role that pointed forward to Jesus as our eternal High Priest.",
    verse: "Aaron held up Moses' hands, one on each side, so they remained steady till sunset.",
    verseRef: "Exodus 17:12",
  },
  {
    name: "BENJAMIN",
    pronunciation: "BEN-juh-min",
    meaning: "Son of My Right Hand",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "Benjamin was the youngest of Jacob's twelve sons — the baby of the family and the full brother of Joseph. When Joseph (who had been sold into slavery) finally revealed himself to his brothers in Egypt, the first thing he asked was 'Is my father still alive? Is Benjamin all right?' Benjamin's tribe later produced Israel's first king, Saul, and also the apostle Paul, who proudly called himself 'of the tribe of Benjamin.'",
    verse: "Then he fell on his brother Benjamin's neck and wept, and Benjamin wept on his neck.",
    verseRef: "Genesis 45:14",
  },
  {
    name: "SIMEON",
    pronunciation: "SIM-ee-un",
    meaning: "He Has Heard",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "There are two famous Simeons in Scripture. The first was one of Jacob's twelve sons. The second was an elderly man in Jerusalem who had been promised by the Holy Spirit that he would not die before seeing the Messiah. When Mary and Joseph brought the baby Jesus to the Temple for dedication, Simeon was led there by the Spirit, took the infant Jesus in his arms, and praised God — saying he could now die in peace because he had seen salvation with his own eyes.",
    verse: "Sovereign Lord, as you have promised, you may now dismiss your servant in peace. For my eyes have seen your salvation.",
    verseRef: "Luke 2:29-30",
  },
  {
    name: "ELISHA",
    pronunciation: "ee-LY-shuh",
    meaning: "My God is Salvation",
    testament: "OT",
    gender: "male",
    pack: "prophets",
    story: "When the prophet Elijah was taken to heaven in a fiery chariot, his protégé Elisha picked up the mantle that fell — literally. Elisha went on to perform twice as many miracles as Elijah: he purified a poisoned water supply, multiplied a widow's oil, raised a boy from the dead, healed a Syrian general named Naaman of leprosy, and even caused an iron axhead to float on water. His ministry was a preview of the miracle-working Jesus who was still to come.",
    verse: "Elisha said, 'What can be done for you? Tell me, what do you have in your house?' 'Your servant has nothing there at all,' she said, 'except a small jar of olive oil.'",
    verseRef: "2 Kings 4:2",
  },
  {
    name: "HABAKKUK",
    pronunciation: "huh-BAK-uk",
    meaning: "Embrace",
    testament: "OT",
    gender: "male",
    pack: "prophets",
    story: "Habakkuk is the prophet who argued with God — and God answered him. He cried out 'How long, Lord, must I call for help and you do not listen?' God responded with a vision and the famous declaration 'The righteous will live by faith.' Habakkuk's book ends with one of the most stunning acts of faith in the Bible: even if every crop fails, every animal dies, and every source of income disappears — still I will rejoice in God. Pure, stubborn, defiant faith.",
    verse: "Though the fig tree does not bud and there are no grapes on the vines... yet I will rejoice in the Lord, I will be joyful in God my Savior.",
    verseRef: "Habakkuk 3:17-18",
  },
  {
    name: "ZADOK",
    pronunciation: "ZAY-dok",
    meaning: "Righteous, Just",
    testament: "OT",
    gender: "male",
    pack: "kings",
    story: "Zadok was the faithful High Priest who stayed loyal to King David even when David's own son Absalom led a rebellion against him. While another priest defected to the rebels, Zadok carried the Ark of the Covenant out of Jerusalem with David — then David told him to take it back, saying 'If I find favor in the Lord's eyes, he will bring me back.' Zadok's descendants served as priests in Solomon's Temple for generations, honored for their faithfulness.",
    verse: "The king also said to Zadok the priest, 'Go back to the city in peace, you and Abiathar. Take the ark of God back into the city.'",
    verseRef: "2 Samuel 15:27",
  },
  {
    name: "OBADIAH",
    pronunciation: "oh-buh-DY-uh",
    meaning: "Servant of God",
    testament: "OT",
    gender: "male",
    pack: "prophets",
    story: "There are multiple Obadiahs in Scripture, but the most remarkable was a palace official under the evil King Ahab who secretly feared God and risked his life by hiding 100 prophets in caves and feeding them bread and water while Queen Jezebel was hunting down and killing all of God's prophets. He is an example of quiet, courageous faithfulness behind the scenes — serving God in the middle of a corrupt system without anyone knowing.",
    verse: "Obadiah was a devout believer in the Lord. While Jezebel was killing off the Lord's prophets, Obadiah had taken a hundred prophets and hidden them in two caves.",
    verseRef: "1 Kings 18:3-4",
  },
  {
    name: "LEMUEL",
    pronunciation: "LEM-yoo-el",
    meaning: "Devoted to God",
    testament: "OT",
    gender: "male",
    pack: "kings",
    story: "Lemuel was a king whose name appears in the book of Proverbs — and the wise words recorded there were actually taught to him by his mother. She warned him not to waste his strength on women who ruin kings, and not to drink wine and forget the decrees of justice. She also described for him the ideal woman of character, which became the famous 'Proverbs 31 woman' passage. Lemuel's story reminds us that wise mothers shape great leaders.",
    verse: "Speak up for those who cannot speak for themselves, for the rights of all who are destitute.",
    verseRef: "Proverbs 31:8",
  },
  {
    name: "OBED",
    pronunciation: "OH-bed",
    meaning: "Servant, Worshiper",
    testament: "OT",
    gender: "male",
    pack: "heroes",
    story: "Obed was the son of Ruth and Boaz — born out of a love story that crossed cultural lines. When the baby was born, the women of Bethlehem celebrated with Naomi, saying 'He will renew your life and sustain you in your old age.' Little Obed became the father of Jesse, who became the father of King David, who became an ancestor of Jesus. One baby, born to a foreign widow and a faithful man, changed the entire story of the world.",
    verse: "Then Naomi took the child in her arms and cared for him. The women living there said, 'Naomi has a son!'",
    verseRef: "Ruth 4:16-17",
  },
  // ── MORE NEW TESTAMENT ──
  {
    name: "LUKE",
    pronunciation: "LOOK",
    meaning: "Light, Illumination",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Luke was a physician — the only Gentile (non-Jewish) author in the entire Bible. He was also Paul's loyal companion and traveled with him on his missionary journeys. Luke wrote both the Gospel of Luke and the book of Acts, giving us the most detailed accounts of Jesus' life and the early church. He interviewed eyewitnesses, did careful research, and wrote with a doctor's eye for detail. His compassion for the sick, the poor, and the outcast shines through every chapter.",
    verse: "Many have undertaken to draw up an account of the things that have been fulfilled among us... I too decided to write an orderly account for you.",
    verseRef: "Luke 1:1,3",
  },
  {
    name: "MARK",
    pronunciation: "MARK",
    meaning: "Of Mars, Warlike",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Mark had a rough start in ministry — he quit a missionary journey with Paul and Barnabas, which made Paul so upset that Paul refused to take him on the next trip. But Barnabas stuck with Mark and mentored him. Years later, Paul himself wrote 'Get Mark and bring him with you, because he is helpful to me in my ministry.' Mark's Gospel is the shortest and most action-packed — written for busy Romans who needed the facts fast. His comeback story is one of the great second-chance stories in the Bible.",
    verse: "Get Mark and bring him with you, because he is helpful to me in my ministry.",
    verseRef: "2 Timothy 4:11",
  },
  {
    name: "TITUS",
    pronunciation: "TY-tus",
    meaning: "Of the Giants, Honored",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Titus was a young Greek man who became one of Paul's most trusted representatives. Paul left him on the island of Crete with a tough assignment — organizing the churches there, appointing elders, and dealing with a culture that had a reputation for lying and laziness. Paul's letter to Titus is full of practical wisdom about leading with integrity. Titus is proof that God calls young leaders and equips them for hard places.",
    verse: "The reason I left you in Crete was that you might put in order what was left unfinished and appoint elders in every town.",
    verseRef: "Titus 1:5",
  },
  {
    name: "PHILEMON",
    pronunciation: "fih-LEE-mun",
    meaning: "Affectionate, Friendly",
    testament: "NT",
    gender: "male",
    pack: "new_testament",
    story: "Philemon was a wealthy Christian man who hosted a church in his house. When his runaway slave Onesimus was converted to faith through Paul's ministry, Paul wrote the most personal letter in the Bible — asking Philemon to receive Onesimus back not as property but as a beloved brother in Christ. This short letter quietly laid a groundwork that the Gospel ultimately destroys every wall between human beings.",
    verse: "I am sending him back to you — sending my very heart. Perhaps the reason he was separated from you for a little while was that you might have him back forever.",
    verseRef: "Philemon 1:12,15",
  },
];
